### ISSUE TITLE
`./cli deposit ...` failed with `nonce too low`

### ISSUE THREAD

**Issue by reverendus** [gnosis/dx-services#17]
```
./cli deposit 9900 DAI

  *********  DutchX CLI - staging  *********
    Operation: deposit 9900 DAI
    Markets: CENSORED
    Ethereum Node: https://mainnet.infura.io
  *********************************

Secp256k1 bindings are not compiled. Pure JS implementation will be used.
2018-10-03T05:09:14.285Z INFO-cli Deposit 9900 DAI into the DX for 0xCENSORED
2018-10-03T05:09:14.287Z INFO-dx-service:services:DxTradeService Fund the account 0xCENSORED with 9.9e+21 DAI

2018-10-03T05:10:40.722Z INFO-dx-service:services:DxTradeService Approved the DX to use 9900 DAI on behalf of the user. Transaction: 0xCENSORED
2018-10-03T05:10:42.737Z ERROR-dx-service:repositories:AuctionRepoImpl Error on transaction "deposit", from "0xCENSORED". Params: [0xCENSORED,9.9e+21]. Gas: 108952, GasPrice: 5000000000. Error: Error: nonce too low
Error: nonce too low
    at /usr/src/app/node_modules/web3-provider-engine/subproviders/provider.js:19:36
    at XMLHttpRequest.request.onreadystatechange (/usr/src/app/node_modules/web3/lib/web3/httpprovider.js:118:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/src/app/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/usr/src/app/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/src/app/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
cli.js deposit <amount> <token> [--acount account]

Deposit the DX account depositing tokens into it

Positionals:
  amount   Amount to buy, i.e. 0.8  [required]
  token    Name of the token, i.e. WETH  [string] [required]
  account  Address were you send the tokens  [string]

Options:
  --version  Show version number  [boolean]
  -h         Show help  [boolean]

Error: nonce too low
    at /usr/src/app/node_modules/web3-provider-engine/subproviders/provider.js:19:36
    at XMLHttpRequest.request.onreadystatechange (/usr/src/app/node_modules/web3/lib/web3/httpprovider.js:118:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/src/app/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/usr/src/app/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/src/app/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

```
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
gnosispm/dx-services               staging             21e79b39597e        7 days ago          409MB
```

```
docker pull gnosispm/dx-services:staging
staging: Pulling from gnosispm/dx-services
Digest: sha256:09f761a0fb0174261e54487290a2994780cfa6ef31fd08ffbf595392c3a01c06
Status: Image is up to date for gnosispm/dx-services:staging
```

**Comment by anxolin** [comment]
Hi @reverendus ! 

Yes, it seems that it has to do with sending the transactions too close.
Our web3 provider takes the nonce from the count of transactions (using `pending` so we take the mempool into account).

We've been doing now a improvement so we can avoid this kind of problems. It's in our `development` branch, is done but not ready to be merged to `master` yet.

@dasanra , can you try to reproduce it and check if in development is fixed? If that's the case, for the time being, just for the `CLI` you can use the `development` tag image in Docker hub (https://hub.docker.com/r/gnosispm/dx-services/tags/).
