### ISSUE TITLE
Claim script tries to claim a future auction

### ISSUE THREAD

**Issue by ben-kaufman** [gnosis/dx-services#30]
Current ongoing auctuion state:
```
  *********  DutchX CLI - v0.7.11  *********
    Docker image: gnosispm/dx-services:v0.7.11
    Config file: ./conf/bots.js
    Run command: node src/cli/cli.js state GEN-WETH
  *********************************

[CLI] Getting docker image: gnosispm/dx-services:v0.7.11...
v0.7.11: Pulling from gnosispm/dx-services
Digest: sha256:9a7d788b93d60a80eede06250e73d85273c4edbd833591800258c9c8921418aa
Status: Image is up to date for gnosispm/dx-services:v0.7.11

[CLI] Run docker...
Secp256k1 bindings are not compiled. Pure JS implementation will be used.

2018-11-21T08:23:39.459Z INFO-cli
**********  State of GEN-WETH  **********

2018-11-21T08:23:39.460Z INFO-cli       Token pair: GEN-WETH

2018-11-21T08:23:39.460Z INFO-cli       Has the token pair been added? Yes
2018-11-21T08:23:39.460Z INFO-cli       State: WAITING_FOR_FUNDING

2018-11-21T08:23:39.461Z INFO-cli       Are tokens Approved?
2018-11-21T08:23:39.461Z INFO-cli               - GEN: No
2018-11-21T08:23:39.461Z INFO-cli               - WETH: No

2018-11-21T08:23:39.462Z INFO-cli       State info:
2018-11-21T08:23:39.462Z INFO-cli               - auctionIndex: 88
2018-11-21T08:23:39.462Z INFO-cli               - auctionStart: null
2018-11-21T08:23:39.463Z INFO-cli
2018-11-21T08:23:39.463Z INFO-cli       Auction GEN-WETH:
2018-11-21T08:23:39.463Z INFO-cli               Is closed: Theoretically closed
2018-11-21T08:23:39.463Z INFO-cli               Sell volume:
2018-11-21T08:23:39.464Z INFO-cli                       sellVolume: 4725.799288585764 GEN
2018-11-21T08:23:39.464Z INFO-cli                       sellVolume: 221.77818465725542 USD
2018-11-21T08:23:39.464Z INFO-cli               Price:
2018-11-21T08:23:39.465Z INFO-cli                       Current Price: 0 GEN/WETH
2018-11-21T08:23:39.466Z INFO-cli                       Previous closing Price: 0.000363792583813195 GEN/WETH
2018-11-21T08:23:39.466Z INFO-cli                       Price relation: N/A
2018-11-21T08:23:39.466Z INFO-cli               Buy volume:
2018-11-21T08:23:39.467Z INFO-cli                       buyVolume: 0 WETH
2018-11-21T08:23:39.467Z INFO-cli                       Bought percentage: 100.0000 %
2018-11-21T08:23:39.467Z INFO-cli
2018-11-21T08:23:39.468Z INFO-cli       Auction WETH-GEN:
2018-11-21T08:23:39.468Z INFO-cli               Is closed: No
2018-11-21T08:23:39.468Z INFO-cli               Sell volume: 0
2018-11-21T08:23:39.469Z INFO-cli
**************************************
```

Logs from running the claim script:
```
2018-11-21T08:21:19.714Z INFO-dx-service:tasks:claimFunds Claiming funds
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
2018-11-21T08:21:21.752Z INFO-dx-service:tasks:claimFunds Claiming for address 0x038cb2d468461dff612abb01d6ae40ab59c1a9c5 affected bots: Main buyer bot, Main seller bot
2018-11-21T08:21:22.846Z INFO-dx-service:services:DxTradeService I have to claim from 1 auctions as seller
2018-11-21T08:21:22.846Z INFO-dx-service:services:DxTradeService Claiming as seller GEN-WETH for auctions: 87,88
Error: gas required exceeds allowance or always failing transaction
    at /usr/src/app/node_modules/truffle-hdwallet-provider/node_modules/web3-provider-engine/subproviders/provider.js:19:36
    at XMLHttpRequest.request.onreadystatechange (/usr/src/app/node_modules/web3/lib/web3/httpprovider.js:118:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/src/app/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/usr/src/app/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/src/app/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

It basically tries to claim funds from auction 88.
I tried doing claiming manually one by one with the CLI, and it turns out that it should have been claiming 86 and 87, while it trys to claim 87 and 88.

**Comment by anxolin** [comment]
Thanks for reporting.

I think there's an issue claiming during a WAITING PERIOD, they usually last 10min so we never encountered this before.

We'll do a fix soon
