### ISSUE TITLE
Claim-tokens command always ends with an error

### ISSUE THREAD

**Issue by johnerfx** [gnosis/dx-services#64]
Claim-tokens command ends like this:

```
cli claim-tokens <token-pairs> [count]

Claim tokens for N auctions of a token pair (i.e. claim-tokens WETH-RDN)

Positionals:
  token-pairs  The token pair of the auction, i.e. WETH-RDN,WETH-OMG  [string] [required]
  count        The number of elements, i.e. 5  [number] [default: 5]

Options:
  --version  Show version number  [boolean]
  -h         Show help  [boolean]

TypeError: Cannot read property 'tx' of undefined
    at Object.handler (/usr/src/app/src/cli/cliCommands/claimTokensCmd.js:32:34)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

```
Transaction is being broadcasted and tokens are being claimed, but execution of the whole script always fails.

**Comment by dasanra** [comment]
Service method response was updated recently. It may be that the command is not getting the expected response parameters to print the transaction result.

Thank you for reporting
