### ISSUE TITLE
`cli balances` does not work with Infura

### ISSUE THREAD

**Issue by reverendus** [gnosis/dx-services#7]
```
➜  dx-examples-liquidity-bots git:(master) ✗ ./cli balances

  *********  DutchX CLI - staging  *********
    Operation: balances
    Markets: WETH-DAI,WETH-MKR,MKR-DAI
    Ethereum Node: https://rinkeby.infura.io
  *********************************

Secp256k1 bindings are not compiled. Pure JS implementation will be used.
2018-08-29T11:23:56.085Z INFO-cli
**********  Balance for 0xc32cac63823b556e6ebf61bb74149f08bf1aab34  **********


2018-08-29T11:23:56.649Z INFO-cli 	ACCOUNT: 0xc32cac63823b556e6ebf61bb74149f08bf1aab34
2018-08-29T11:23:56.650Z INFO-cli 	BALANCE: 1.229053568 ETH
cli.js balances

Get the balances for all known tokens for a given account. If no account selected mnemonic account is used (i.e. )

Options:
  --version      Show version number  [boolean]
  -h             Show help  [boolean]
  --account      Address were you send the tokens  [string]
  --verbose, -v  Extra info about tokens is showed  [boolean]

Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/usr/src/app/node_modules/web3/lib/web3/errors.js:35:16)
    at XMLHttpRequest.request.onreadystatechange (/usr/src/app/node_modules/web3/lib/web3/httpprovider.js:115:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/src/app/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/usr/src/app/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/src/app/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

```
➜  dx-examples-liquidity-bots git:(master) ✗ cat ./cli
#!/usr/bin/env bash

# Config
MARKETS=WETH-DAI,WETH-MKR,MKR-DAI
WETH_TOKEN_ADDRESS=0xc58b96a0278bd2c77bc93e01b148282fb8e753a5
ETHEREUM_RPC_URL=https://rinkeby.infura.io
NETWORK=rinkeby
MNEMONIC="....."
RDN_TOKEN_ADDRESS=0x3615757011112560521536258c1e7325ae3b48ae
DAI_TOKEN_ADDRESS=0x62f25065BA60CA3A2044344955A3B2530e355111
MKR_TOKEN_ADDRESS=0x2D9585690A724BfA29a212295a9E8C714ca694aA
DX_SERVICE_VERSION=staging

# Get the params
CLI_PARAMS=${@:--h}

echo
echo "  *********  DutchX CLI - $DX_SERVICE_VERSION  *********"
echo "    Operation: $CLI_PARAMS"
echo "    Markets: $MARKETS"
echo "    Ethereum Node: $ETHEREUM_RPC_URL"
echo "  *********************************"
echo

docker run \
  -e MNEMONIC="$MNEMONIC" \
  -e ETHEREUM_RPC_URL=$ETHEREUM_RPC_URL \
  -e MARKETS=$MARKETS \
  -e NETWORK=$NETWORK \
  -e WETH_TOKEN_ADDRESS=$WETH_TOKEN_ADDRESS \
  -e RDN_TOKEN_ADDRESS=$RDN_TOKEN_ADDRESS \
  -e DAI_TOKEN_ADDRESS=$DAI_TOKEN_ADDRESS \
  -e MKR_TOKEN_ADDRESS=$MKR_TOKEN_ADDRESS \
  gnosispm/dx-services:$DX_SERVICE_VERSION \
  npm run --silent cli -- $CLI_PARAMS```

**Comment by reverendus** [comment]
Works fine now, both with Infura and with a local geth node.
Closing.
