### ISSUE TITLE
`cli balances` does not work with a local geth node

### ISSUE THREAD

**Issue by reverendus** [gnosis/dx-services#8]
```➜  dx-examples-liquidity-bots git:(master) ✗ ./cli balances 0xc32cac63823b556e6ebf61bb74149f08bf1aab34

  *********  DutchX CLI - staging  *********
    Operation: balances 0xc32cac63823b556e6ebf61bb74149f08bf1aab34
    Markets: WETH-DAI,WETH-MKR,MKR-DAI
    Ethereum Node: https://rinkeby.infura.io
  *********************************

Secp256k1 bindings are not compiled. Pure JS implementation will be used.
2018-08-29T11:31:39.279Z INFO-cli
**********  Balance for 0xc32cac63823b556e6ebf61bb74149f08bf1aab34  **********


2018-08-29T11:31:39.286Z INFO-cli 	ACCOUNT: 0xc32cac63823b556e6ebf61bb74149f08bf1aab34
2018-08-29T11:31:39.287Z INFO-cli 	BALANCE: 1.229053568 ETH
cli.js balances

Get the balances for all known tokens for a given account. If no account selected mnemonic account is used (i.e. )

Options:
  --version      Show version number  [boolean]
  -h             Show help  [boolean]
  --account      Address were you send the tokens  [string]
  --verbose, -v  Extra info about tokens is showed  [boolean]

{ AssertionError [ERR_ASSERTION]: The token is required
    at AuctionRepoImpl.getBalance (/usr/src/app/src/repositories/AuctionRepo/AuctionRepoImpl.js:389:5)
    at DxInfoService.getAccountBalanceForToken (/usr/src/app/src/services/DxInfoService.js:542:30)
    at Promise.all.tokens.map (/usr/src/app/src/cli/cliCommands/balancesCmd.js:54:29)
    at Array.map (<anonymous>)
    at Object.handler (/usr/src/app/src/cli/cliCommands/balancesCmd.js:42:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: null,
  expected: true,
  operator: '==' }
```

note there is a `-e ETHEREUM_RPC_URL=http://192.168.99.1:8545` variable in the script below which points it to a local geth node

```➜  dx-examples-liquidity-bots git:(master) ✗ cat ./cli
#!/usr/bin/env bash

# Config
MARKETS=WETH-DAI,WETH-MKR,MKR-DAI
WETH_TOKEN_ADDRESS=0xc58b96a0278bd2c77bc93e01b148282fb8e753a5
ETHEREUM_RPC_URL=https://rinkeby.infura.io
NETWORK=rinkeby
MNEMONIC="..."
RDN_TOKEN_ADDRESS=0x3615757011112560521536258c1e7325ae3b48ae
DAI_TOKEN_ADDRESS=0x62f25065BA60CA3A2044344955A3B2530e355111
MKR_TOKEN_ADDRESS=0x2D9585690A724BfA29a212295a9E8C714ca694aA
DX_SERVICE_VERSION=staging

# Get the params
CLI_PARAMS=${@:--h}

echo
echo "  *********  DutchX CLI - $DX_SERVICE_VERSION  *********"
echo "    Operation: $CLI_PARAMS"
echo "    Markets: $MARKETS"
echo "    Ethereum Node: $ETHEREUM_RPC_URL"
echo "  *********************************"
echo

docker run \
  -e MNEMONIC="$MNEMONIC" \
  -e ETHEREUM_RPC_URL=$ETHEREUM_RPC_URL \
  -e MARKETS=$MARKETS \
  -e NETWORK=$NETWORK \
  -e WETH_TOKEN_ADDRESS=$WETH_TOKEN_ADDRESS \
  -e RDN_TOKEN_ADDRESS=$RDN_TOKEN_ADDRESS \
  -e DAI_TOKEN_ADDRESS=$DAI_TOKEN_ADDRESS \
  -e MKR_TOKEN_ADDRESS=$MKR_TOKEN_ADDRESS \
  -e ETHEREUM_RPC_URL=http://192.168.99.1:8545 \
  gnosispm/dx-services:$DX_SERVICE_VERSION \
  npm run --silent cli -- $CLI_PARAMS```

**Comment by reverendus** [comment]
Works fine now, both with Infura and with a local geth node.
Closing.
